### ISSUE TITLE
Textbox for the Grabbed Links

### ISSUE THREAD

**Issue by MirisWisdom** [lap00zza/Grabber#8]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
After the grabbing is completed, the fetched episode URLs should be stored in a textbox for the users to copy and paste from if they (accidentally) override the clipboard with something else.

**Comment by lap00zza** [comment]
This is added in #17
